name: breakdown_server_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  convert: ^3.1.1
  flutter:
    sdk: flutter
  http: ^0.13.6
  socket_io: ^1.0.1
  socket_io_client: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
